

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace API.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MainDBModelContainer : DbContext
{
    public MainDBModelContainer()
        : base("name=MainDBModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Project> ProjectSet { get; set; }

    public virtual DbSet<Team> TeamSet { get; set; }

    public virtual DbSet<User> UserSet { get; set; }

    public virtual DbSet<Role> RoleSet { get; set; }

    public virtual DbSet<ProjectStatus> ProjectStatusSet { get; set; }

    public virtual DbSet<Milestone> MilestoneSet { get; set; }

    public virtual DbSet<Client> ClientSet { get; set; }

    public virtual DbSet<Task> TaskSet { get; set; }

    public virtual DbSet<TaskStatus> TaskStatusSet { get; set; }

    public virtual DbSet<TaskPriority> TaskPrioritySet { get; set; }

    public virtual DbSet<Commit> CommitSet { get; set; }

    public virtual DbSet<TaskLog> TaskLogSet { get; set; }

}

}

