
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Milestone
{

    public Milestone()
    {

        this.Task = new HashSet<Task>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public System.DateTime EndDate { get; set; }



    public virtual Project Project { get; set; }

    public virtual ICollection<Task> Task { get; set; }

}

}
