
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    public Project()
    {

        this.Team = new HashSet<Team>();

        this.Milestone = new HashSet<Milestone>();

        this.Task = new HashSet<Task>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string CreatedOn { get; set; }

    public string Client { get; set; }

    public string Status { get; set; }

    public string ProjectManager { get; set; }



    public virtual ICollection<Team> Team { get; set; }

    public virtual ProjectStatus ProjectStatus { get; set; }

    public virtual ICollection<Milestone> Milestone { get; set; }

    public virtual Client Client1 { get; set; }

    public virtual ICollection<Task> Task { get; set; }

}

}
