
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Team
{

    public Team()
    {

        this.Project = new HashSet<Project>();

        this.User = new HashSet<User>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string TeamLead { get; set; }



    public virtual ICollection<Project> Project { get; set; }

    public virtual ICollection<User> User { get; set; }

}

}
