
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int Id { get; set; }

    public string Username { get; set; }

    public string Passkey { get; set; }

    public string Email { get; set; }

    public string Firstname { get; set; }

    public System.DateTime DateOfBirth { get; set; }

    public System.DateTime LastActivity { get; set; }

    public string Roles { get; set; }

    public Nullable<int> Task_Id { get; set; }



    public virtual Team Team { get; set; }

}

}
